### ISSUE TITLE
open menu keybind

### ISSUE THREAD

**Issue by frankthe3rd** [EclipseMenu/EclipseMenu#112]
### What feature would you like to see?

I can't open the menu since I have mega hack. Mega hack's only menu keybind is tab. Is there a way that you could add something like a "choose menu keybind" in mod settings or custom keybinds? Mega hack only has the feature to add more menu keybinds, not replace the original TAB one.

**Comment by FireMario211** [comment]
@frankthe3rd turn on the fallback keybind for mega hack, then press tab, and change the keybind by going to the keybinds section of Eclipse
![image](https://github.com/user-attachments/assets/1c9a81ea-c6bb-4f2c-b007-1293af7a447a)
that is where you can change your keybind
