### ISSUE TITLE
hitbox expander

### ISSUE THREAD

**Issue by NoobLikesThis** [EclipseMenu/EclipseMenu#114]
### What feature would you like to see?

i would like to see a hitbox expander feature, like megahack does.

**Comment by FireMario211** [comment]
unsure what youre talking about but it already exists
![image](https://github.com/user-attachments/assets/5fa59a85-f997-463c-866e-da0d43ccf75c)
![image](https://github.com/user-attachments/assets/2b50fa1d-a61c-41a0-9079-61ac9a321945)

**Comment by NoobLikesThis** [comment]
o

**Comment by NoobLikesThis** [comment]
ty
