### ISSUE TITLE
Windows are all in the same location by default

### ISSUE THREAD

**Issue by zkayns** [EclipseMenu/EclipseMenu#3]
By default, all hack windows are in the same location, and if more windows are added in the future, it will be tedious to manually move them all apart.

**Comment by maxnut** [comment]
this menu is being actively worked on, its not supposed to be public yet, no point in posting these kind of issues

**Comment by Rustring** [comment]
@maxnut Transparent lists makes everything bug out lol

**Comment by maxnut** [comment]
> @maxnut Transparent lists makes everything bug out lol

hi hello um quick question do you have a brain? do you have eyes? reading? you know what that is? this is not out to the public yet!!!! dont report issues in github, especially like this! thanks

**Comment by FireMario211** [comment]
i wanna disable issues so people dont complain to us on a project that isn't even in beta yet

**Comment by Rustring** [comment]
> > @maxnut Transparent lists makes everything bug out lol
> 
> hi hello um quick question do you have a brain? do you have eyes? reading? you know what that is? this is not out to the public yet!!!! dont report issues in github, especially like this! thanks

I didn't say anything I just commented

**Comment by Rustring** [comment]
> i wanna disable issues so people dont complain to us on a project that isn't even in beta yet

Yeah do

**Comment by FireMario211** [comment]
@Rustring why are you distributing releases if this said project isnt done? youre just going to have people complain about this project which isn't even supposed to be out for the public yet

**Comment by Rustring** [comment]
> @Rustring why are you distributing releases if this said project isnt done? youre just going to have people complain about this project which isn't even supposed to be out for the public yet

@FireMario211 I'll delete the releases

**Comment by zkayns** [comment]
> @maxnut Transparent lists makes everything bug out lol

mister why are you replying to closed issue with unrelated problem this very bad

**Comment by FireMario211** [comment]
hi my name is Firee

**Comment by CuteistFox** [comment]
This is out to the public, but if you dont want people to be helpfull and tell you that something is broken, dont make this public

**Comment by maxnut** [comment]
> This is out to the public, but if you dont want people to be helpfull and tell you that something is broken, dont make this public

while yes, you can technically get a release through the github action since they are public, those are meant as a developer resource, not as a user resource. a public release would be found in the releases section of the repository. do you see any releases there?

**Comment by CuteistFox** [comment]
No, but it is a public release as anyone who knows how to use nightly.link can get them
