### ISSUE TITLE
Not available on Geode

### ISSUE THREAD

**Issue by CrimsonFork** [EclipseMenu/EclipseMenu#31]
https://geode-sdk.org/mods?query=eclipse ([Internet Archive snapshot](https://web.archive.org/web/20241007175815/https://geode-sdk.org/mods?query=eclipse).)
![Screenshot from 2024-10-07 19-55-02](https://github.com/user-attachments/assets/4fe76a52-1dcf-4249-8f28-d09af7b997b6)

**Comment by FireMario211** [comment]
duh, wait till the premiere!

**Comment by CrimsonFork** [comment]
Ah, fair enough, LOL, didn't know it can be reliably timed like this.

**Comment by FireMario211** [comment]
it is now out
