### ISSUE TITLE
Smart startpos crashes the game

### ISSUE THREAD

**Issue by BreakloafGD** [EclipseMenu/EclipseMenu#39]

**Comment by BreakloafGD** [comment]
[2024-10-08_15-33-05.log](https://github.com/user-attachments/files/17292567/2024-10-08_15-33-05.log)
crashlog

**Comment by CatsAnarchy** [comment]
This is a known bug on macos and is being worked on

**Comment by BreakloafGD** [comment]
now it works thanks :)
