### ISSUE TITLE
Sugestion: Add "total attempts" to the labels, a way to rearrange the labels and maybe a list of all the commends I can put in "text" like {cps}, {clicks}, {time} and {attempts}

### ISSUE THREAD

**Issue by BWGucio** [EclipseMenu/EclipseMenu#41]
I hope I not asking for too much. I just like labels

**Comment by Prevter** [comment]
Total attempts is already in there, check variables list:
https://github.com/EclipseMenu/EclipseMenu/blob/main/LABELS.md
