### ISSUE TITLE
SUGGESTION: add noclip accuracy and deaths plus one more thing

### ISSUE THREAD

**Issue by smilybean246** [EclipseMenu/EclipseMenu#48]
This is amazing, especially for releasing less than a week ago, but it would be a great addition if noclip accuracy and noclip deaths were added to this.
Another thing is that it would be a good idea to add pitch shift and audio speed as settings for speedhack so you don't have to change each individual one.

These are both just suggestions and suggestions aren't that important but I just wanted to give you some ideas.
Have an amazing day!

**Comment by FireMario211** [comment]
Noclip Accuracy and Deaths already exist, also placing all of those under one Speedhack would sort of make it confusing
