### ISSUE TITLE
hitboxes break when rotating an object in the editor

### ISSUE THREAD

**Issue by 2847asuer** [EclipseMenu/EclipseMenu#57]

**Comment by Prevter** [comment]
if you're talking about slopes, that's vanilla bug

**Comment by 2847asuer** [comment]
oh

**Comment by 2847asuer** [comment]
<img width="847" alt="Ekran Resmi 2024-10-12 20 34 38" src="https://github.com/user-attachments/assets/4b4d54a4-9e95-4313-a913-8ca2cd3b6e5f">

**Comment by 2847asuer** [comment]
I hope someone can fix this

**Comment by Prevter** [comment]
that's something more fit for "Misc Bugfixes" mod by Cvolton
