### ISSUE TITLE
SHOW TRAJECTORY AND NOCLIP IS PERMANETLY ENABLED

### ISSUE THREAD

**Issue by smilybean246** [EclipseMenu/EclipseMenu#65]
I was playing an extreme demon when i dropped my controller (i was doing a challenge) on my keyboard and now show trajectory AND noclip are permanently stuck on. I don't know what to do and this had made the game unplayable. I tried pressing every button on my keyboard but nothing reverted it. I also checked the hacking client and it said show trajectory and noclip were NOT enabled. I have no clue what's going on. If you need me to, I can attach some photos to this and show you what I mean.

Please help because I don't know what is happening.

**Comment by Prevter** [comment]
do you have them enabled somewhere else, like xdbot?

**Comment by smilybean246** [comment]
Yeah I do... sorry for wasting your time lol.
