### ISSUE TITLE
Playing a level crashes the game!!! On MacOS

### ISSUE THREAD

**Issue by FireDasher** [EclipseMenu/EclipseMenu#66]
I just got Eclipse for the first time and i clicked play on a level and it CRASHED!!!!!!!!!!! I didn't have ANY mods enabled and it kept crashing!!!!!!!!!!!!!!!!!111111111111111111111111111111

# PLEASE FIX

**Comment by CatsAnarchy** [comment]
...you expect eclipse to fix a bug when you dont even attach a crash dump?

**Comment by FireMario211** [comment]
> ...you expect eclipse to fix the bug when you dont even attach a crash dump?

i have a feeling its the same node ids crash every mac user is reporting, though yeah they should do that for next time tbh...

**Comment by FireDasher** [comment]
uh sorry this is old report

**Comment by FireDasher** [comment]
most crashes fixed with geode updates and stuff
