### ISSUE TITLE
EDITOR EXTENSION

### ISSUE THREAD

**Issue by heavyutils** [EclipseMenu/EclipseMenu#69]
Free scroll is pretty much useless without editor extension. Suggestion is to add editor extension but combine it into free scroll as theyre both useless without each other
Edit: To be clear, editor extension is what allows you to move and edit blocks outside the normal range, and free scroll allows you to see blocks outside the normal range.

**Comment by FireMario211** [comment]
Duplicate of https://github.com/EclipseMenu/EclipseMenu/issues/51
