### ISSUE TITLE
Conflicts with tobyadd.gdh (steam proton)

### ISSUE THREAD

**Issue by aceinetx** [EclipseMenu/EclipseMenu#71]
Crashes at startup with exception access violation
Crash log:
```
2024-10-19T10:44:48+0300
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "geode.node-ids" mod. Please submit this crash report to its developers (Geode Team) for assistance.

== Geode Information ==
Loader Version: v3.8.1
Loader Commit: 47e0ca5
Bindings Commit: 7fbb83d
Installed mods: 41
Problems: 1

== Exception Information ==
Faulty Module: Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll
Faulty Mod: Node IDs v1.15.0 (geode.node-ids)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00006FFFFB57F680 (geode.node-ids.dll + df680)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + df680
 - 0000000000D18882 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 2e6f5e
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 37df0
 - 0000000000D18882 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 1da466
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 17dcb6
 - 00000000018B8082 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.level-id-api\cvolton.level-id-api.dll + 11ec8
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.level-id-api\cvolton.level-id-api.dll + 85fd
 - 00000000018B8082 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 69745
 - 00000000018DF882 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\km7dev.gdps-switcher\km7dev.gdps-switcher.dll + 1cf71
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\km7dev.gdps-switcher\km7dev.gdps-switcher.dll + 8d12
 - 00000000018DF882 (Hook handler)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 172bf7
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 80fee
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 7299b
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\Geode.dll + 2910da (gdMainHook + 554 | Z:\home\runner\work\geode\geode\loader\src\platform\windows\main.cpp:181)
 - Z:\home\aceinet\.local\share\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\windows\system32\kernel32.dll + 1482d
 - C:\windows\system32\ntdll.dll + f44f

== Register States ==
RAX: 00006ffffb57f680
RBX: 0000000000000000
RCX: 74ba57f694ee0000
RDX: 000000000000000c
RBP: 0000000000000000
RSP: 000000000011ffb0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00006ffffff4f44f
R8:  0000000000000006
R9:  00006ffffffaf800
R10: 0000000000000000
R11: 0000000000801800
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
~ | [v1.0.0] aceinet.level_edit
~ | [v0.3.3-alpha] alk.allium
~ | [v1.0.4] alk.wave_trail_snap
~ | [v1.0.5] alphalaneous.editortab_api
x | [v1.5.3] alphalaneous.happy_textures
~ | [v1.1.3] alphalaneous.object_summary
~ | [v1.0.1] alphalaneous.settings_everywhere
~ | [v1.0.0] anatom3000.functional
~ | [v1.8.3] beat.click-sound
~ | [v1.0.0] bry400.no_block_glow
x | [v4.2.11] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
~ | [v1.0.3] dogotrigger.partmanager
x | [v1.0.0-beta.3] eclipse.eclipse-menu
~ | [v1.0.1] fig.authentication
~ | [v1.3.1] firee.object-workshop
~ | [v0.3.2] flafy.autonong
~ | [v2.11.0] fleym.nongd
~ | [v1.9.0] geode.custom-keybinds
~ | [v1.7.0] geode.devtools
x | [v3.8.1] geode.loader
x | [v1.15.0] geode.node-ids
~ | [v1.0.10] hiimjustin000.more_object_info
~ | [v1.1.0] hjfod.backups
~ | [v6.7.0] hjfod.betteredit
~ | [v1.3.0] hjfod.gdshare
~ | [v1.2.1] hjfod.gmd-api
~ | [v1.0.0] hjfod.trashcan
x | [v1.1.4] km7dev.gdps-switcher
~ | [v1.3.4] legowiifun.unlisted_objects_in_editor
~ | [v1.1.0] midair.fullscreen_keybind
~ | [v1.0.0] ndrnmnk.gdps_archive
~ | [v1.3.0] nytelyte.wave_trail_drag_fix
~ | [v1.0.0] sabe.trailfix
~ | [v1.2.2] shineua.geometrize2gd
x | [v1.6.10] thesillydoggo.qolmod
! | [v4.7.6] tobyadd.gdh
~ | [v1.1.4] weebify.restartbtn
~ | [v1.0.2] zeozeozeo.zcblive
~ | [v2.0.0-beta.7] zilko.xdbot
```
When tobyadd.gdh is disabled it's working fine

**Comment by TobyAdd** [comment]
Maybe some hack could be causing the crash. Try resetting GDH settings. Go to `%localappdata%\GeometryDash\geode\mods\tobyadd.gdh` and remove config.json file

**Comment by aceinetx** [comment]
> Maybe some hack could be causing the crash. Try resetting GDH settings. Go to `%localappdata%\GeometryDash\geode\mods\tobyadd.gdh` and remove config.json file

Didn't fix the issue, I had enabled only like 3 hacks so it surely has nothing to do with them

**Comment by FireMario211** [comment]
![image](https://github.com/user-attachments/assets/c562e6df-5592-476e-81eb-8d4c637d382e)
gdh and eclipse work fine for me

**Comment by aceinetx** [comment]
> ![image](https://github.com/user-attachments/assets/c562e6df-5592-476e-81eb-8d4c637d382e)
> gdh and eclipse work fine for me

Are you on linux with steam proton? If so I have no idea why this happens on my machine

**Comment by aceinetx** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/17692105/378912773-c562e6df-5592-476e-81eb-8d4c637d382e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTg2MTMsIm5iZiI6MTcyOTYxODMxMywicGF0aCI6Ii8xNzY5MjEwNS8zNzg5MTI3NzMtYzU2MmU2ZGYtNTU5Mi00NzZlLTgxZWItOGQ0YzYzN2QzODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE3MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NWUxMzY3MGUwZDRhNTc2YTcwMzU0ODcyNmVhNDNiODQ5Yzc4YzM5ZDQ3YTk2YmNhNjc0YThmN2ZkZThkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1jYYLi_drIA6vMI07IZkiWZFGCR8Nt8cA3OvEDEg7Js)
> > > gdh and eclipse work fine for me
> > 
> > Are you on linux with steam proton? If so I have no idea why this happens on my machine
> 
> im a linux user, so yes
> though I use wine, not proton, but it shouldn't make a difference.

That's strange, maybe some mod could be causing the crash, I'll try disabling some mods

**Comment by Superpro12341147** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/17692105/378912773-c562e6df-5592-476e-81eb-8d4c637d382e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTg2MTMsIm5iZiI6MTcyOTYxODMxMywicGF0aCI6Ii8xNzY5MjEwNS8zNzg5MTI3NzMtYzU2MmU2ZGYtNTU5Mi00NzZlLTgxZWItOGQ0YzYzN2QzODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE3MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NWUxMzY3MGUwZDRhNTc2YTcwMzU0ODcyNmVhNDNiODQ5Yzc4YzM5ZDQ3YTk2YmNhNjc0YThmN2ZkZThkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1jYYLi_drIA6vMI07IZkiWZFGCR8Nt8cA3OvEDEg7Js)
> > > > gdh and eclipse work fine for me
> > > 
> > > 
> > > Are you on linux with steam proton? If so I have no idea why this happens on my machine
> > 
> > 
> > im a linux user, so yes
> though I use wine, not proton, but it shouldn't make a difference.

my guess its different but me not on linux so idk
