### ISSUE TITLE
Where are raw videos (ffmpeg) located at?

### ISSUE THREAD

**Issue by FoxoThatCat** [EclipseMenu/EclipseMenu#72]
I recorded the video and i dont know where its located at

I use Windows 11

**Comment by FireMario211** [comment]
copied from the Eclipse Menu server in case you are not in it

## Where are macros/renders located?
You can find them in the
"game save directory" > "geode" > "mods" > "eclipse.eclipse-menu"

You can use the "Save folder" button to quickly open the directory, and then navigate to the correct folder.

**For Windows users**:
You can press `Win`+`R` to bring up the "Run" box, and then enter "`%LocalAppData%/GeometryDash/geode/mods/eclipse.eclipse-menu`".
