### ISSUE TITLE
max cps value

### ISSUE THREAD

**Issue by wedgelixir** [EclipseMenu/EclipseMenu#84]
i want to make  a max cps label, but idk what the value is
![image](https://github.com/user-attachments/assets/483f6d5d-95bf-48d6-9fa9-862b9fa58c27)

**Comment by Prevter** [comment]
`{maxCps}`
https://github.com/EclipseMenu/EclipseMenu/blob/main/LABELS.md#clicks-information

**Comment by wedgelixir** [comment]
thank you
