### ISSUE TITLE
Support for GD 2.2074

### ISSUE THREAD

**Issue by styalos** [EclipseMenu/EclipseMenu#98]
### What feature would you like to see?

I saw the showcase on YouTube and immediately decided to replace QOLMod with it. Then when i installed it, Geode said that the mod menu was for version 2.206 and i was using 2.2074. I'd request support for the version now than later since the latest beta was on 10/13.

**Comment by LobotomyHubXD** [comment]
https://github.com/EclipseMenu/EclipseMenu/actions/runs/12040656755/artifacts/2241779187

Unstable latest build, it supports 2.2074.

**Comment by LobotomyHubXD** [comment]
@styalos

**Comment by styalos** [comment]
where da api at?

**Comment by LobotomyHubXD** [comment]
@styalos https://github.com/EclipseMenu/ffmpeg-api/releases

**Comment by LobotomyHubXD** [comment]
Also official release came @styalos
